services:
  web:
    image: f20250983/metro_project:v10
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "python manage.py migrate --noinput &&
      gunicorn metro_system.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: always
    volumes:
      - static_volume:/home/metro_system/web/staticfiles/
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abhiraj
      POSTGRES_DB: database
  nginx-internal:
    build: ./nginx
    ports:
      - "127.0.0.1:8080:80"  # bridge connection from 127001:8080 to container:80
    volumes:
      - ./nginx/internal.conf:/etc/nginx/conf.d/default.conf 
      - static_volume:/home/metro_system/web/staticfiles/
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # renew every 12 hours
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  static_volume:
